/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.debugger.evaluate;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@RunWith(JUnit3RunnerWithInners.class)
public class KotlinEvaluateExpressionTestGenerated extends AbstractKotlinEvaluateExpressionTest {
    @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class SingleBreakpoint extends AbstractKotlinEvaluateExpressionTest {
        @TestMetadata("abstractFunCall.kt")
        public void testAbstractFunCall() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/abstractFunCall.kt");
        }

        @TestMetadata("accessToOverridenPropertyWithBackingField.kt")
        public void testAccessToOverridenPropertyWithBackingField() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/accessToOverridenPropertyWithBackingField.kt");
        }

        public void testAllFilesPresentInSingleBreakpoint() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("annotationValue.kt")
        public void testAnnotationValue() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/annotationValue.kt");
        }

        @TestMetadata("anonymousObjects.kt")
        public void testAnonymousObjects() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/anonymousObjects.kt");
        }

        @TestMetadata("arrays.kt")
        public void testArrays() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/arrays.kt");
        }

        @TestMetadata("boxParam.kt")
        public void testBoxParam() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/boxParam.kt");
        }

        @TestMetadata("boxReturnValue.kt")
        public void testBoxReturnValue() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/boxReturnValue.kt");
        }

        @TestMetadata("breakpointInInlineFun.kt")
        public void testBreakpointInInlineFun() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/breakpointInInlineFun.kt");
        }

        @TestMetadata("callableBug.kt")
        public void testCallableBug() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/callableBug.kt");
        }

        @TestMetadata("classFromAnotherPackage.kt")
        public void testClassFromAnotherPackage() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/classFromAnotherPackage.kt");
        }

        @TestMetadata("classObjectVal.kt")
        public void testClassObjectVal() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/classObjectVal.kt");
        }

        @TestMetadata("collections.kt")
        public void testCollections() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/collections.kt");
        }

        @TestMetadata("delegatedPropertyInOtherFile.kt")
        public void testDelegatedPropertyInOtherFile() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/delegatedPropertyInOtherFile.kt");
        }

        @TestMetadata("dependentOnFile.kt")
        public void testDependentOnFile() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/dependentOnFile.kt");
        }

        @TestMetadata("doubles.kt")
        public void testDoubles() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/doubles.kt");
        }

        @TestMetadata("enums.kt")
        public void testEnums() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/enums.kt");
        }

        @TestMetadata("errors.kt")
        public void testErrors() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/errors.kt");
        }

        @TestMetadata("extractLocalVariables.kt")
        public void testExtractLocalVariables() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extractLocalVariables.kt");
        }

        @TestMetadata("extractThis.kt")
        public void testExtractThis() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extractThis.kt");
        }

        @TestMetadata("extractThisInTrait.kt")
        public void testExtractThisInTrait() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extractThisInTrait.kt");
        }

        @TestMetadata("extractVariablesFromCall.kt")
        public void testExtractVariablesFromCall() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extractVariablesFromCall.kt");
        }

        @TestMetadata("fileWithError.kt")
        public void testFileWithError() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/fileWithError.kt");
        }

        @TestMetadata("funFromSuperClass.kt")
        public void testFunFromSuperClass() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/funFromSuperClass.kt");
        }

        @TestMetadata("genericCrossinlineArgument.kt")
        public void testGenericCrossinlineArgument() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/genericCrossinlineArgument.kt");
        }

        @TestMetadata("imports.kt")
        public void testImports() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/imports.kt");
        }

        @TestMetadata("importsLambdaContext.kt")
        public void testImportsLambdaContext() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/importsLambdaContext.kt");
        }

        @TestMetadata("inlineFunInMultiFilePackage.kt")
        public void testInlineFunInMultiFilePackage() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/inlineFunInMultiFilePackage.kt");
        }

        @TestMetadata("inlineFunction.kt")
        public void testInlineFunction() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/inlineFunction.kt");
        }

        @TestMetadata("inlineFunctionBreakpointAnotherFile.kt")
        public void testInlineFunctionBreakpointAnotherFile() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/inlineFunctionBreakpointAnotherFile.kt");
        }

        @TestMetadata("inlineFunctionBreakpointVariants.kt")
        public void testInlineFunctionBreakpointVariants() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/inlineFunctionBreakpointVariants.kt");
        }

        @TestMetadata("innerClass.kt")
        public void testInnerClass() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/innerClass.kt");
        }

        @TestMetadata("insertInBlock.kt")
        public void testInsertInBlock() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/insertInBlock.kt");
        }

        @TestMetadata("internalFunctionEvaluate.kt")
        public void testInternalFunctionEvaluate() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/internalFunctionEvaluate.kt");
        }

        @TestMetadata("internalProperty.kt")
        public void testInternalProperty() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/internalProperty.kt");
        }

        @TestMetadata("kt12206BasePropertyWithoutBackingField.kt")
        public void testKt12206BasePropertyWithoutBackingField() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/kt12206BasePropertyWithoutBackingField.kt");
        }

        @TestMetadata("kt17514.kt")
        public void testKt17514() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/kt17514.kt");
        }

        @TestMetadata("kt5554OnlyIntsShouldBeCoerced.kt")
        public void testKt5554OnlyIntsShouldBeCoerced() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/kt5554OnlyIntsShouldBeCoerced.kt");
        }

        @TestMetadata("kt7046localVarInInline.kt")
        public void testKt7046localVarInInline() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/kt7046localVarInInline.kt");
        }

        @TestMetadata("localClass.kt")
        public void testLocalClass() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/localClass.kt");
        }

        @TestMetadata("localVariables.kt")
        public void testLocalVariables() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/localVariables.kt");
        }

        @TestMetadata("methodWithBreakpoint.kt")
        public void testMethodWithBreakpoint() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/methodWithBreakpoint.kt");
        }

        @TestMetadata("multilineExpressionAtBreakpoint.kt")
        public void testMultilineExpressionAtBreakpoint() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/multilineExpressionAtBreakpoint.kt");
        }

        @TestMetadata("nestedInlineArguments.kt")
        public void testNestedInlineArguments() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/nestedInlineArguments.kt");
        }

        @TestMetadata("onClassHeader.kt")
        public void testOnClassHeader() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/onClassHeader.kt");
        }

        @TestMetadata("onGetter.kt")
        public void testOnGetter() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/onGetter.kt");
        }

        @TestMetadata("onObjectHeader.kt")
        public void testOnObjectHeader() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/onObjectHeader.kt");
        }

        @TestMetadata("package.kt")
        public void testPackage() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/package.kt");
        }

        @TestMetadata("parametersOfInlineFun.kt")
        public void testParametersOfInlineFun() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/parametersOfInlineFun.kt");
        }

        @TestMetadata("parametersOfInlineFunSeveralOnLine.kt")
        public void testParametersOfInlineFunSeveralOnLine() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/parametersOfInlineFunSeveralOnLine.kt");
        }

        @TestMetadata("privateClass.kt")
        public void testPrivateClass() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/privateClass.kt");
        }

        @TestMetadata("privateMember.kt")
        public void testPrivateMember() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/privateMember.kt");
        }

        @TestMetadata("privatePropertyWithExplicitDefaultGetter.kt")
        public void testPrivatePropertyWithExplicitDefaultGetter() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/privatePropertyWithExplicitDefaultGetter.kt");
        }

        @TestMetadata("protectedMember.kt")
        public void testProtectedMember() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/protectedMember.kt");
        }

        @TestMetadata("rawTypeskt11831.kt")
        public void testRawTypeskt11831() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/rawTypeskt11831.kt");
        }

        @TestMetadata("simple.kt")
        public void testSimple() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/simple.kt");
        }

        @TestMetadata("stdlib.kt")
        public void testStdlib() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/stdlib.kt");
        }

        @TestMetadata("typeParameterRef.kt")
        public void testTypeParameterRef() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/typeParameterRef.kt");
        }

        @TestMetadata("unboxParam.kt")
        public void testUnboxParam() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/unboxParam.kt");
        }

        @TestMetadata("unsafeCall.kt")
        public void testUnsafeCall() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/unsafeCall.kt");
        }

        @TestMetadata("vars.kt")
        public void testVars() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/vars.kt");
        }

        @TestMetadata(".kt.kt")
        public void test_kt() throws Exception {
            KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/.kt.kt");
        }

        @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class CompilingEvaluator extends AbstractKotlinEvaluateExpressionTest {
            public void testAllFilesPresentInCompilingEvaluator() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("ceAnonymousObject.kt")
            public void testCeAnonymousObject() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceAnonymousObject.kt");
            }

            @TestMetadata("ceAnonymousObjectCapturedInClosure.kt")
            public void testCeAnonymousObjectCapturedInClosure() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceAnonymousObjectCapturedInClosure.kt");
            }

            @TestMetadata("ceAnonymousObjectThisAsReceiver.kt")
            public void testCeAnonymousObjectThisAsReceiver() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceAnonymousObjectThisAsReceiver.kt");
            }

            @TestMetadata("ceLambda.kt")
            public void testCeLambda() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceLambda.kt");
            }

            @TestMetadata("ceLocalClass.kt")
            public void testCeLocalClass() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceLocalClass.kt");
            }

            @TestMetadata("ceLocalClassMembers.kt")
            public void testCeLocalClassMembers() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceLocalClassMembers.kt");
            }

            @TestMetadata("ceLocalClassWithSuperClass.kt")
            public void testCeLocalClassWithSuperClass() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceLocalClassWithSuperClass.kt");
            }

            @TestMetadata("ceMembers.kt")
            public void testCeMembers() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceMembers.kt");
            }

            @TestMetadata("ceObject.kt")
            public void testCeObject() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceObject.kt");
            }

            @TestMetadata("ceSeveralLambdas.kt")
            public void testCeSeveralLambdas() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceSeveralLambdas.kt");
            }

            @TestMetadata("ceSuperAccess.kt")
            public void testCeSuperAccess() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/compilingEvaluator/ceSuperAccess.kt");
            }
        }

        @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/createExpression")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class CreateExpression extends AbstractKotlinEvaluateExpressionTest {
            public void testAllFilesPresentInCreateExpression() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/createExpression"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("createExpressionCastToBuiltIn.kt")
            public void testCreateExpressionCastToBuiltIn() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/createExpression/createExpressionCastToBuiltIn.kt");
            }

            @TestMetadata("createExpressionSimple.kt")
            public void testCreateExpressionSimple() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/createExpression/createExpressionSimple.kt");
            }

            @TestMetadata("createExpressionWithArray.kt")
            public void testCreateExpressionWithArray() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/createExpression/createExpressionWithArray.kt");
            }
        }

        @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class ExtraVariables extends AbstractKotlinEvaluateExpressionTest {
            public void testAllFilesPresentInExtraVariables() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("evBreakpointOnPropertyDeclaration.kt")
            public void testEvBreakpointOnPropertyDeclaration() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evBreakpointOnPropertyDeclaration.kt");
            }

            @TestMetadata("evDelegatedProperty.kt")
            public void testEvDelegatedProperty() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evDelegatedProperty.kt");
            }

            @TestMetadata("evDuplicateItems.kt")
            public void testEvDuplicateItems() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evDuplicateItems.kt");
            }

            @TestMetadata("evFinalProperty.kt")
            public void testEvFinalProperty() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evFinalProperty.kt");
            }

            @TestMetadata("evFunctionDeclaration.kt")
            public void testEvFunctionDeclaration() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evFunctionDeclaration.kt");
            }

            @TestMetadata("evLineRange.kt")
            public void testEvLineRange() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evLineRange.kt");
            }

            @TestMetadata("evProperty.kt")
            public void testEvProperty() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evProperty.kt");
            }

            @TestMetadata("evPropertyRefExpr.kt")
            public void testEvPropertyRefExpr() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evPropertyRefExpr.kt");
            }

            @TestMetadata("evSkipAnonymousObject.kt")
            public void testEvSkipAnonymousObject() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evSkipAnonymousObject.kt");
            }

            @TestMetadata("evSkipLambda.kt")
            public void testEvSkipLambda() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evSkipLambda.kt");
            }

            @TestMetadata("evSkipLocalClass.kt")
            public void testEvSkipLocalClass() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/extraVariables/evSkipLocalClass.kt");
            }
        }

        @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Frame extends AbstractKotlinEvaluateExpressionTest {
            public void testAllFilesPresentInFrame() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("catchVariable.kt")
            public void testCatchVariable() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/catchVariable.kt");
            }

            @TestMetadata("delegatedPropertyInClass.kt")
            public void testDelegatedPropertyInClass() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/delegatedPropertyInClass.kt");
            }

            @TestMetadata("delegatedPropertyInClassWithToString.kt")
            public void testDelegatedPropertyInClassWithToString() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/delegatedPropertyInClassWithToString.kt");
            }

            @TestMetadata("delegatedPropertyInClassWoRenderer.kt")
            public void testDelegatedPropertyInClassWoRenderer() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/delegatedPropertyInClassWoRenderer.kt");
            }

            @TestMetadata("frameAnonymousObject.kt")
            public void testFrameAnonymousObject() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameAnonymousObject.kt");
            }

            @TestMetadata("frameClassObject.kt")
            public void testFrameClassObject() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameClassObject.kt");
            }

            @TestMetadata("frameClosingBracket.kt")
            public void testFrameClosingBracket() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameClosingBracket.kt");
            }

            @TestMetadata("frameExtFunExtFun.kt")
            public void testFrameExtFunExtFun() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameExtFunExtFun.kt");
            }

            @TestMetadata("frameExtensionFun.kt")
            public void testFrameExtensionFun() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameExtensionFun.kt");
            }

            @TestMetadata("frameInlineArgument.kt")
            public void testFrameInlineArgument() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameInlineArgument.kt");
            }

            @TestMetadata("frameInlineArgumentInsideInlineFun.kt")
            public void testFrameInlineArgumentInsideInlineFun() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameInlineArgumentInsideInlineFun.kt");
            }

            @TestMetadata("frameInlineFun.kt")
            public void testFrameInlineFun() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameInlineFun.kt");
            }

            @TestMetadata("frameInlineFunCallInsideInlineFun.kt")
            public void testFrameInlineFunCallInsideInlineFun() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameInlineFunCallInsideInlineFun.kt");
            }

            @TestMetadata("frameInnerClass.kt")
            public void testFrameInnerClass() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameInnerClass.kt");
            }

            @TestMetadata("frameInnerLambda.kt")
            public void testFrameInnerLambda() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameInnerLambda.kt");
            }

            @TestMetadata("frameLambda.kt")
            public void testFrameLambda() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameLambda.kt");
            }

            @TestMetadata("frameLambdaNotUsed.kt")
            public void testFrameLambdaNotUsed() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameLambdaNotUsed.kt");
            }

            @TestMetadata("frameLocalVariable.kt")
            public void testFrameLocalVariable() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameLocalVariable.kt");
            }

            @TestMetadata("frameObject.kt")
            public void testFrameObject() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameObject.kt");
            }

            @TestMetadata("frameSharedVar.kt")
            public void testFrameSharedVar() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameSharedVar.kt");
            }

            @TestMetadata("frameSharedVarLocalVar.kt")
            public void testFrameSharedVarLocalVar() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameSharedVarLocalVar.kt");
            }

            @TestMetadata("frameSimple.kt")
            public void testFrameSimple() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameSimple.kt");
            }

            @TestMetadata("frameThis0.kt")
            public void testFrameThis0() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameThis0.kt");
            }

            @TestMetadata("frameThis0Ext.kt")
            public void testFrameThis0Ext() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameThis0Ext.kt");
            }

            @TestMetadata("frameThis0This0.kt")
            public void testFrameThis0This0() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/frame/frameThis0This0.kt");
            }
        }

        @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/javaContext")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class JavaContext extends AbstractKotlinEvaluateExpressionTest {
            public void testAllFilesPresentInJavaContext() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/javaContext"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("jcBlock.kt")
            public void testJcBlock() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/javaContext/jcBlock.kt");
            }

            @TestMetadata("jcImports.kt")
            public void testJcImports() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/javaContext/jcImports.kt");
            }

            @TestMetadata("jcLocalVariable.kt")
            public void testJcLocalVariable() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/javaContext/jcLocalVariable.kt");
            }

            @TestMetadata("jcMarkedObject.kt")
            public void testJcMarkedObject() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/javaContext/jcMarkedObject.kt");
            }

            @TestMetadata("jcProperty.kt")
            public void testJcProperty() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/javaContext/jcProperty.kt");
            }

            @TestMetadata("jcSimple.kt")
            public void testJcSimple() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/javaContext/jcSimple.kt");
            }
        }

        @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/labels")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Labels extends AbstractKotlinEvaluateExpressionTest {
            public void testAllFilesPresentInLabels() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/labels"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("lCallOnLabeledObj.kt")
            public void testLCallOnLabeledObj() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/labels/lCallOnLabeledObj.kt");
            }

            @TestMetadata("lIdentifier.kt")
            public void testLIdentifier() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/labels/lIdentifier.kt");
            }

            @TestMetadata("lSeveralLabels.kt")
            public void testLSeveralLabels() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/labels/lSeveralLabels.kt");
            }

            @TestMetadata("lSimple.kt")
            public void testLSimple() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/labels/lSimple.kt");
            }

            @TestMetadata("ldifferentTypes.kt")
            public void testLdifferentTypes() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/labels/ldifferentTypes.kt");
            }
        }

        @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Lambdas extends AbstractKotlinEvaluateExpressionTest {
            public void testAllFilesPresentInLambdas() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("destructuringParam.kt")
            public void testDestructuringParam() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/destructuringParam.kt");
            }

            @TestMetadata("inlineFunctionalExpression.kt")
            public void testInlineFunctionalExpression() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/inlineFunctionalExpression.kt");
            }

            @TestMetadata("inlineLambda.kt")
            public void testInlineLambda() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/inlineLambda.kt");
            }

            @TestMetadata("lambdaOnReturn.kt")
            public void testLambdaOnReturn() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/lambdaOnReturn.kt");
            }

            @TestMetadata("lambdaOnSecondLine.kt")
            public void testLambdaOnSecondLine() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/lambdaOnSecondLine.kt");
            }

            @TestMetadata("oneLineFunctionalExpression.kt")
            public void testOneLineFunctionalExpression() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/oneLineFunctionalExpression.kt");
            }

            @TestMetadata("oneLineLambda.kt")
            public void testOneLineLambda() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/oneLineLambda.kt");
            }

            @TestMetadata("twoLambdasOnOneLineFirst.kt")
            public void testTwoLambdasOnOneLineFirst() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/twoLambdasOnOneLineFirst.kt");
            }

            @TestMetadata("twoLambdasOnOneLineSecond.kt")
            public void testTwoLambdasOnOneLineSecond() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/twoLambdasOnOneLineSecond.kt");
            }

            @TestMetadata("underscoreNames.kt")
            public void testUnderscoreNames() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/lambdas/underscoreNames.kt");
            }
        }

        @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/renderer")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Renderer extends AbstractKotlinEvaluateExpressionTest {
            public void testAllFilesPresentInRenderer() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/renderer"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("toStringRenderer.kt")
            public void testToStringRenderer() throws Exception {
                KotlinTestUtils.runTest(this::doSingleBreakpointTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/singleBreakpoint/renderer/toStringRenderer.kt");
            }
        }
    }

    @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class MultipleBreakpoints extends AbstractKotlinEvaluateExpressionTest {
        public void testAllFilesPresentInMultipleBreakpoints() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("clearCache.kt")
        public void testClearCache() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/clearCache.kt");
        }

        @TestMetadata("constructors.kt")
        public void testConstructors() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/constructors.kt");
        }

        @TestMetadata("exceptions.kt")
        public void testExceptions() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/exceptions.kt");
        }

        @TestMetadata("extensionMemberFunction.kt")
        public void testExtensionMemberFunction() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/extensionMemberFunction.kt");
        }

        @TestMetadata("extensionMemberFunctionInObject.kt")
        public void testExtensionMemberFunctionInObject() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/extensionMemberFunctionInObject.kt");
        }

        @TestMetadata("extensionMemberProperty.kt")
        public void testExtensionMemberProperty() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/extensionMemberProperty.kt");
        }

        @TestMetadata("funFromOuterClassInLamdba.kt")
        public void testFunFromOuterClassInLamdba() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/funFromOuterClassInLamdba.kt");
        }

        @TestMetadata("initializer.kt")
        public void testInitializer() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/initializer.kt");
        }

        @TestMetadata("invisibleDeclarations.kt")
        public void testInvisibleDeclarations() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/invisibleDeclarations.kt");
        }

        @TestMetadata("isInsideInlineLambda.kt")
        public void testIsInsideInlineLambda() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/isInsideInlineLambda.kt");
        }

        @TestMetadata("localFun.kt")
        public void testLocalFun() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/localFun.kt");
        }

        @TestMetadata("multipleBreakpointsAtLine.kt")
        public void testMultipleBreakpointsAtLine() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/multipleBreakpointsAtLine.kt");
        }

        @TestMetadata("privateMembersPriority.kt")
        public void testPrivateMembersPriority() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/privateMembersPriority.kt");
        }

        @TestMetadata("remappedParameterInInline.kt")
        public void testRemappedParameterInInline() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/remappedParameterInInline.kt");
        }

        @TestMetadata("smartcasts.kt")
        public void testSmartcasts() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/smartcasts.kt");
        }

        @TestMetadata("whenEntry.kt")
        public void testWhenEntry() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/whenEntry.kt");
        }

        @TestMetadata("withoutBodyFunctions.kt")
        public void testWithoutBodyFunctions() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/withoutBodyFunctions.kt");
        }

        @TestMetadata("withoutBodyProperties.kt")
        public void testWithoutBodyProperties() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/withoutBodyProperties.kt");
        }

        @TestMetadata("withoutBodyProperties2.kt")
        public void testWithoutBodyProperties2() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/withoutBodyProperties2.kt");
        }

        @TestMetadata("withoutBodyTypeParameters.kt")
        public void testWithoutBodyTypeParameters() throws Exception {
            KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/withoutBodyTypeParameters.kt");
        }

        @TestMetadata("idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/library")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Library extends AbstractKotlinEvaluateExpressionTest {
            public void testAllFilesPresentInLibrary() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/library"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("customLibClassName.kt")
            public void testCustomLibClassName() throws Exception {
                KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/library/customLibClassName.kt");
            }

            @TestMetadata("localFunInLibrary.kt")
            public void testLocalFunInLibrary() throws Exception {
                KotlinTestUtils.runTest(this::doMultipleBreakpointsTest,TargetBackend.ANY, "idea/testData/debugger/tinyApp/src/evaluate/multipleBreakpoints/library/localFunInLibrary.kt");
            }
        }
    }
}
