/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.caches.resolve;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("idea/testData/multiModuleLineMarker")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class MultiModuleLineMarkerTestGenerated extends AbstractMultiModuleLineMarkerTest {
    @TestMetadata("actualEnumEntries")
    public void testActualEnumEntries() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/actualEnumEntries/");
    }

    public void testAllFilesPresentInMultiModuleLineMarker() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/multiModuleLineMarker"), Pattern.compile("^([^\\.]+)$"), TargetBackend.ANY, false);
    }

    @TestMetadata("expectEnumEntries")
    public void testExpectEnumEntries() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/expectEnumEntries/");
    }

    @TestMetadata("fromActualAnnotation")
    public void testFromActualAnnotation() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromActualAnnotation/");
    }

    @TestMetadata("fromActualPrimaryConstructor")
    public void testFromActualPrimaryConstructor() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromActualPrimaryConstructor/");
    }

    @TestMetadata("fromActualSealedClass")
    public void testFromActualSealedClass() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromActualSealedClass/");
    }

    @TestMetadata("fromActualSecondaryConstructor")
    public void testFromActualSecondaryConstructor() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromActualSecondaryConstructor/");
    }

    @TestMetadata("fromActualTypeAlias")
    public void testFromActualTypeAlias() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromActualTypeAlias/");
    }

    @TestMetadata("fromClassToAlias")
    public void testFromClassToAlias() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromClassToAlias/");
    }

    @TestMetadata("fromClassToJavaAliasInTest")
    public void testFromClassToJavaAliasInTest() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromClassToJavaAliasInTest/");
    }

    @TestMetadata("fromCommonToJvmHeader")
    public void testFromCommonToJvmHeader() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromCommonToJvmHeader/");
    }

    @TestMetadata("fromCommonToJvmImpl")
    public void testFromCommonToJvmImpl() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromCommonToJvmImpl/");
    }

    @TestMetadata("fromExpectedAnnotation")
    public void testFromExpectedAnnotation() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromExpectedAnnotation/");
    }

    @TestMetadata("fromExpectedPrimaryConstructor")
    public void testFromExpectedPrimaryConstructor() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromExpectedPrimaryConstructor/");
    }

    @TestMetadata("fromExpectedSealedClass")
    public void testFromExpectedSealedClass() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromExpectedSealedClass/");
    }

    @TestMetadata("fromExpectedSecondaryConstructor")
    public void testFromExpectedSecondaryConstructor() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromExpectedSecondaryConstructor/");
    }

    @TestMetadata("fromExpectedTypeAlias")
    public void testFromExpectedTypeAlias() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/fromExpectedTypeAlias/");
    }

    @TestMetadata("hierarchyWithExpectClassCommonSide")
    public void testHierarchyWithExpectClassCommonSide() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/hierarchyWithExpectClassCommonSide/");
    }

    @TestMetadata("hierarchyWithExpectClassCommonSideNonJavaIds")
    public void testHierarchyWithExpectClassCommonSideNonJavaIds() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/hierarchyWithExpectClassCommonSideNonJavaIds/");
    }

    @TestMetadata("hierarchyWithExpectClassPlatformSide")
    public void testHierarchyWithExpectClassPlatformSide() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/hierarchyWithExpectClassPlatformSide/");
    }

    @TestMetadata("kotlinTestAnnotations")
    public void testKotlinTestAnnotations() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/kotlinTestAnnotations/");
    }

    @TestMetadata("suspendImplInPlatformModules")
    public void testSuspendImplInPlatformModules() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/suspendImplInPlatformModules/");
    }

    @TestMetadata("topLevelFunWithKotlinTest")
    public void testTopLevelFunWithKotlinTest() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/topLevelFunWithKotlinTest/");
    }

    @TestMetadata("transitive")
    public void testTransitive() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/transitive/");
    }

    @TestMetadata("transitiveCommon")
    public void testTransitiveCommon() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/transitiveCommon/");
    }

    @TestMetadata("withOverloads")
    public void testWithOverloads() throws Exception {
        KotlinTestUtils.runTest(this::doTest,TargetBackend.ANY, "idea/testData/multiModuleLineMarker/withOverloads/");
    }
}
